name: copy files
on: [push]

jobs:
  Copy-README-to-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: execute
        run: node copy.js
